
version: '3'

services:
        postgres:
                image: postgres
                environment:
                        POSTGRES_DB: quantify
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_USER: postgres
                hostname: postgres

        app:
                build: .
                ports:
                        - 5000:5000
                depends_on:
                        - postgres
